verify dependencies and use env for each step

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,10 +8,6 @@ on:
       - master
 
 jobs:
-  env:
-    ARTIFACT: 'bidrag-dokument-dto'
-    IMAGE: 'maven:3.6.2-jdk-12'
-    M2_REPO: '.m2/repository'
 
   checkout:
     steps:
@@ -20,9 +16,34 @@ jobs:
       - name: debug
         run: env
 
-  maven:
+  verify-dependencies:
     needs: checkout
+    env:
+      ARTIFACT: 'bidrag-dokument-dto'
+      IMAGE: 'maven:3.6.2-jdk-12'
+      M2_REPO: '.m2/repository'
+
+    steps:
+      - name: verify that no dependencies is of type SNAPSHOT
+      - run: |
+          docker run --rm --name "$ARTIFACT:dependencies" \
+            -v "$HOME/.m2":/root/.m2 \
+            -v "$PWD":/usr/src/maven \
+            -w /usr/src/maven "$IMAGE" mvn -B install > dependency.tree
+          export NUM_OF_SNAPSHOT_DEPENDENCIES="$(cat dependency.tree | grep - | grep -v :test | grep -v $ARTIFACT | grep -c SNAPSHOT )"
+          if [ ! $NUM_OF_SNAPSHOT_DEPENDENCIES==0 ]
+            then
+              >&2 echo "[ERROR] Found $NUM_OF_SNAPSHOT_DEPENDENCIES in $ARTFIFACT"
+              exit 1;
+          fi
+
+  maven:
+    needs: verify-dependencies
     runs-on: ubuntu-latest
+    env:
+      ARTIFACT: 'bidrag-dokument-dto'
+      IMAGE: 'maven:3.6.2-jdk-12'
+      M2_REPO: '.m2/repository'
 
     steps:
       - uses: actions/cache@v1
@@ -44,6 +65,11 @@ jobs:
 
     if: startsWith(github.event.commits[0].message, 'Bump patch version') == false
 
+    env:
+      ARTIFACT: 'bidrag-dokument-dto'
+      IMAGE: 'maven:3.6.2-jdk-12'
+      M2_REPO: '.m2/repository'
+
     steps:
       - uses: actions/cache@v1
         with:
@@ -57,7 +83,7 @@ jobs:
             -v "$HOME/.m2":/root/.m2 \
             -v "$PWD":/usr/src/maven \
             -w /usr/src/maven "$IMAGE" mvn -B release:update-version
-          export BUMP_VERSION="$(cat pom.xml | grep  version | grep -e SNAPSHOT | sed 's:version::g' | sed 's:[< />]::g')"
+          export BUMP_VERSION="$(cat pom.xml | grep version | grep -e SNAPSHOT | sed 's:version::g' | sed 's:[< />]::g')"
           git add pom.xml
           git commit -m "Bump patch version for $ARTIFACT: $BUMP_VERSION"
           git push
